name: Spoolman
version: 0.22.1.1
description: Run the stable version of Spoolman.
url: https://github.com/dimquea/hassio/tree/main/spoolman
slug: spoolman
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
startup: application
udev: true
webui: "[PROTO:option_name]://[HOST]:[PORT:7912]"
map:
  - addon_config:rw
boot: auto
options:
  log_level: "ERROR"
  auto_backup: true
  debug_mode: false
schema:
  log_level: str
  auto_backup: bool
  base_path: str?
  debug_mode: bool
ports:
  7912/tcp: 7912
